#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      echo brew install linode/cli/linode-cli
      ;;

    Linux)
      echo "deb http://apt.linode.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/linode.list
      wget -O- https://apt.linode.com/linode.gpg | sudo apt-key add -
      sudo aptitude update
      sudo aptitude install -y linode-cli
      ;;
  esac
}

bootstrap
